# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.59.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Dev") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Dev") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Builds the app for development testing"
  lane :development do
    increment_build_number
    appName = "FastlaneExample" + get_version_number + "." + get_build_number
    gym(
      export_method: "development",
      output_name: appName
    ) 
    hockey(
      api_token: "8026bfaff3c045a7bf8f6a8bbaf8d3b9",
      ipa: "./FastlaneExample.ipa",
      notes: "Changelog"
    )
    mailgun(
      to: "jossiestebancs@gmail.com",
      success: true,
      message: "This is the mail's content"
    )
    # sh "your_script.sh"
  end

  desc "Send email using mailgun"
  lane :test_mail_gun do
    mailgun(
      postmaster: "postmaster@sandbox4ad8eb06507b489e9f977d1ee7632283.mailgun.org",
      to: "esteban.chavarria@gorillalogic.com",
      success: true,
      message: "This is the mail's content",
      app_link: "http://www.myapplink.com",
      apikey: "key-e9ea2be81d28ea5b9a3e13f2057a63a0",
      success: false,
    )
  end 

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
